# Generated by Django 2.2.3 on 2019-08-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=10)),
                ('emp_father', models.CharField(max_length=10)),
                ('emp_Email', models.EmailField(max_length=30)),
                ('emp_Id', models.IntegerField()),
            ],
        ),
    ]
